import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/components/providers/modal-provider";
import { SessionProvider, useSession } from "next-auth/react";
import { Session } from 'next-auth'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface props {
  session: Session | null

}

export default function RootLayout(
  {children}: Readonly<{children: React.ReactNode;}>,
  session: Session | null) {

  
  return (
    <html lang="en">
      <body className={inter.className}>
      
        
        <SessionProvider session={session}>
          <ModalProvider />
          {children}
        </SessionProvider>
        </body>
    </html>
  );
}
