import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/components/providers/modal-provider";
import { SessionProvider, useSession } from "next-auth/react";
import { Session } from 'next-auth'
import { ThemeProvider } from "@/components/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout(
  {children}: Readonly<{children: React.ReactNode;}>,
  session: Session | null) {

  
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
      
        
        <SessionProvider session={session}>
          <ThemeProvider
          attribute="class"
          defaultTheme="light"
          enableSystem={false}
          disableTransitionOnChange
          >
            <ModalProvider />
            {children}
            <Toaster />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
